apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neutron-os.fullname" . }}-secrets
  labels:
    {{- include "neutron-os.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgresql-postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  {{- end }}
  anthropic-api-key: {{ "" | b64enc | quote }}
