"""neut model generate — deterministic input deck section generation.

Generates MCNP/MPACT material cards from model.yaml material references.
Same input = same output across runs, machines, and Python versions.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from neutron_os.extensions.builtins.model_corral.materials_db import get_material


def generate_materials(
    model_dir: Path,
    *,
    output_format: str = "mcnp",
    output_file: Path | None = None,
) -> str:
    """Generate material cards from a model's material references.

    Reads model.yaml, resolves material names against the registry,
    and produces deterministic output.

    Args:
        model_dir: Path to model directory containing model.yaml.
        output_format: "mcnp" or "mpact".
        output_file: If provided, write output to this file.

    Returns:
        Generated material card text.
    """
    model_yaml = model_dir / "model.yaml"
    if not model_yaml.exists():
        raise FileNotFoundError(f"model.yaml not found in {model_dir}")

    data = yaml.safe_load(model_yaml.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("model.yaml must be a YAML mapping")

    materials_ref = data.get("materials", [])
    if not materials_ref:
        raise ValueError("No 'materials' section in model.yaml")

    lines = []
    lines.append(_header(data, output_format))

    for i, mat_ref in enumerate(materials_ref, 1):
        mat_name = mat_ref if isinstance(mat_ref, str) else mat_ref.get("name", "")
        mat_number = mat_ref.get("number", i) if isinstance(mat_ref, dict) else i

        mat = get_material(mat_name)
        if mat is None:
            lines.append(f"c  WARNING: material not found: {mat_name}")
            continue

        if output_format == "mcnp":
            lines.append(mat.mcnp_cards(mat_number=mat_number))
        elif output_format == "mpact":
            lines.append(mat.mpact_card())

        lines.append("")  # blank separator

    output = "\n".join(lines)

    if output_file is not None:
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(output, encoding="utf-8")

    return output


def _header(data: dict, fmt: str) -> str:
    """Generate a deterministic header comment."""
    model_id = data.get("model_id", "unknown")
    version = data.get("version", "0.0.0")
    code = data.get("physics_code", "")

    if fmt == "mcnp":
        return (
            f"c  ========================================\n"
            f"c  Materials generated by NeutronOS\n"
            f"c  Model: {model_id} v{version}\n"
            f"c  Code: {code}\n"
            f"c  ========================================"
        )
    elif fmt == "mpact":
        return f"! Materials generated by NeutronOS\n! Model: {model_id} v{version}\n! Code: {code}"
    return ""


def cmd_generate(
    path: str, *, section: str = "materials", output_format: str = "mcnp", output: str | None = None
) -> int:
    """CLI entry point for neut model generate."""
    model_dir = Path(path)

    if section != "materials":
        print(f"Section not yet supported: {section}")
        print("Available: materials")
        return 1

    try:
        result = generate_materials(
            model_dir,
            output_format=output_format,
            output_file=Path(output) if output else None,
        )
        if output:
            print(f"Generated: {output}")
        else:
            print(result)
        return 0
    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}")
        return 1
