#!/usr/bin/env bash
# setup-rascal.sh — Bootstrap PostgreSQL 16 + pgvector on Ubuntu 24.04 (Rascal)
# Usage: sudo ./setup-rascal.sh
set -euo pipefail

DB_NAME="${DB_NAME:-neut_db}"
DB_USER="${DB_USER:-neut}"
DB_PASS="${DB_PASS:-neut_local_dev}"
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCHEMA_SQL="${REPO_ROOT}/infra/db/schema.sql"
ENV_FILE="${REPO_ROOT}/.env"

echo "============================================"
echo "  NeutronOS Rascal — Local Database Setup"
echo "============================================"
echo ""

# -------------------------------------------------------
# 1. Check privileges
# -------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
  echo "[ERROR] This script must be run as root (use sudo)."
  exit 1
fi

# -------------------------------------------------------
# 2. Install PostgreSQL 16
# -------------------------------------------------------
echo "[1/6] Checking PostgreSQL installation..."

if command -v psql &>/dev/null && psql --version | grep -q "16"; then
  echo "       PostgreSQL 16 is already installed."
else
  echo "       Installing PostgreSQL 16..."
  apt-get update -qq
  apt-get install -y -qq postgresql-16 postgresql-client-16
  echo "       PostgreSQL 16 installed."
fi

# -------------------------------------------------------
# 3. Install pgvector extension
# -------------------------------------------------------
echo "[2/6] Checking pgvector extension..."

if dpkg -l | grep -q postgresql-16-pgvector; then
  echo "       pgvector is already installed."
else
  echo "       Installing postgresql-16-pgvector..."
  apt-get install -y -qq postgresql-16-pgvector
  echo "       pgvector installed."
fi

# Ensure PostgreSQL is running
systemctl enable postgresql
systemctl start postgresql

# -------------------------------------------------------
# 4. Create database user
# -------------------------------------------------------
echo "[3/6] Creating database user '${DB_USER}'..."

sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASS}';"

echo "       User '${DB_USER}' ready."

# -------------------------------------------------------
# 5. Create database
# -------------------------------------------------------
echo "[4/6] Creating database '${DB_NAME}'..."

sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"

# Grant privileges
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"
sudo -u postgres psql -d "${DB_NAME}" -c "GRANT ALL ON SCHEMA public TO ${DB_USER};"

echo "       Database '${DB_NAME}' ready."

# -------------------------------------------------------
# 6. Apply schema
# -------------------------------------------------------
echo "[5/6] Applying schema from ${SCHEMA_SQL}..."

if [[ ! -f "${SCHEMA_SQL}" ]]; then
  echo "[ERROR] Schema file not found: ${SCHEMA_SQL}"
  exit 1
fi

PGPASSWORD="${DB_PASS}" psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" -f "${SCHEMA_SQL}"

echo "       Schema applied."

# -------------------------------------------------------
# 7. Write .env file
# -------------------------------------------------------
echo "[6/6] Writing .env file to ${ENV_FILE}..."

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

# Append to .env (don't overwrite — may contain ANTHROPIC_API_KEY etc.)
touch "${ENV_FILE}"
# Remove old DB vars if present
sed -i '/^DATABASE_URL=/d; /^DB_HOST=/d; /^DB_PORT=/d; /^DB_NAME=/d; /^DB_USER=/d; /^DB_PASS=/d' "${ENV_FILE}"
cat >> "${ENV_FILE}" <<EOF

# NeutronOS local database (generated by setup-rascal.sh)
DATABASE_URL=${DATABASE_URL}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
EOF

chmod 600 "${ENV_FILE}"
echo "       .env written."

# -------------------------------------------------------
# Done
# -------------------------------------------------------
echo ""
echo "============================================"
echo "  Setup complete!"
echo "============================================"
echo ""
echo "  Connection string:"
echo "    ${DATABASE_URL}"
echo ""
echo "  Test with:"
echo "    psql '${DATABASE_URL}'"
echo ""
